### ISSUE TITLE
Getting unhandled exception with large volume of data

### ISSUE THREAD

**Issue by akblissweb** [Microsoft/Product-Recommendations#6]
Hi,
I've got the system working with upto 7GB of training data.  But as soon as I try 10GB the program falls over with the following after approx 4 hours.  
Any ideas ?

Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.IOException
   at System.IO.MemoryStream.Write(Byte[], Int32, Int32)
   at Microsoft.MachineLearning.Data.IO.BinarySaver.WriteWorker(System.IO.Stream, System.Collections.Concurrent.BlockingCollection`1<Block>, ColumnCodec[], Microsoft.MachineLearning.Data.ISchema, Int32, Microsoft.MachineLearning.IChannelProvider, Microsoft.MachineLearning.Internal.Utilities.ExceptionMarshaller)

Exception Info: System.InvalidOperationException
   at Microsoft.MachineLearning.Internal.Utilities.ExceptionMarshaller.ThrowIfSet(Microsoft.MachineLearning.IExceptionContext)
   at Microsoft.MachineLearning.Data.IO.BinarySaver.SaveData(System.IO.Stream, Microsoft.MachineLearning.Data.IDataView, Int32[])
   at Microsoft.MachineLearning.Recommend.ItemSimilarity.SimilarityMatrix.Save(Microsoft.MachineLearning.Model.ModelSaveContext)
   at Microsoft.MachineLearning.Model.ModelSaveContext.SaveModel[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](Microsoft.MachineLearning.Model.RepositoryWriter, System.__Canon, System.String)
   at Microsoft.MachineLearning.Recommend.Sar.SarPredictor.Save(Microsoft.MachineLearning.Model.ModelSaveContext)
   at Microsoft.MachineLearning.Model.ModelSaveContext.SaveModel[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](Microsoft.MachineLearning.Model.RepositoryWriter, System.__Canon, System.String)
   at Microsoft.MachineLearning.Data.TrainUtils.SaveModel(Microsoft.MachineLearning.IHostEnvironment, Microsoft.MachineLearning.IChannel, System.IO.Stream, Microsoft.MachineLearning.IPredictor, Microsoft.MachineLearning.Data.RoleMappedData, System.String)
   at Microsoft.MachineLearning.EntryPoints.PredictorModel.Save(Microsoft.MachineLearning.IHostEnvironment, System.IO.Stream)
   at Recommendations.Core.Train.TrainedModel.GetObjectData(System.Runtime.Serialization.SerializationInfo, System.Runtime.Serialization.StreamingContext)
   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize(System.Object, System.Runtime.Serialization.ISurrogateSelector, System.Runtime.Serialization.StreamingContext, System.Runtime.Serialization.Formatters.Binary.SerObjectInfoInit, System.Runtime.Serialization.IFormatterConverter, System.Runtime.Serialization.Formatters.Binary.ObjectWriter, System.Runtime.Serialization.SerializationBinder)
   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.Serialize(System.Object, System.Runtime.Serialization.ISurrogateSelector, System.Runtime.Serialization.StreamingContext, System.Runtime.Serialization.Formatters.Binary.SerObjectInfoInit, System.Runtime.Serialization.IFormatterConverter, System.Runtime.Serialization.Formatters.Binary.ObjectWriter, System.Runtime.Serialization.SerializationBinder)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize(System.Object, System.Runtime.Remoting.Messaging.Header[], System.Runtime.Serialization.Formatters.Binary.__BinaryWriter, Boolean)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(System.IO.Stream, System.Object, System.Runtime.Remoting.Messaging.Header[], Boolean)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(System.IO.Stream, System.Object)
   at Recommendations.Common.ModelsProvider.SerializeTrainedModel(Recommendations.Core.ITrainedModel, System.IO.Stream, System.Guid)

Exception Info: System.Exception
   at Recommendations.Common.ModelsProvider.SerializeTrainedModel(Recommendations.Core.ITrainedModel, System.IO.Stream, System.Guid)
   at Recommendations.Common.ModelsProvider+<TrainAsync>d__1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].GetResult()
   at NativeTrainer.WebJobLogic+<TrainModelAsync>d__3.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter`1[[System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].GetResult()
   at NativeTrainer.WebJobLogic+<TrainModelAsync>d__1.MoveNext()

Exception Info: System.AggregateException
   at NativeTrainer.Program.Main(System.String[])

**Comment by natinimni** [comment]
Hi Akblissweb,

Thank you for sharing this - we’ll try to investigate this failure.
What size machine are you using? did you try to scale up to an SKU with more RAM? (don’t forget to review the price before scaling).

Thanks,
Nati

**Comment by natinimni** [comment]
Hi @akblissweb , 
Please retry now (perhaps also using a machine with more memory) as the service was updated recently - you may use (http://aka.ms/recotemplate) to deploy instances to your Azure subscription. 

Thanks,
Nati
